---
- name: Copying files to remote
  hosts: all

  tasks:
  - name: Copy files #name me hum jo task kar rahe hai uska description dete hai
    copy:
      src: /root/myfile.txt
      dest: /tmp/    # tmp folder me myfile ko copy karna hai    
