---
- name: File Module
  hosts: all
  
  tasks:
  - name: Creating a file
    file:
      path: /tmp/newfile.txt
      state: touch
      owner: sumit
      group: sumit
      mode:  u=rwx,g=rw,o=r

  - name: Creating a Directory
    file:
     path: /tmp/myfolder
     state: directory
          
