---
- name: Cron Setup
  hosts: all

  tasks:
  - name: Add Cron Job
    cron:
      name: Run Test Script
      minute: 20
      hour: 18   
      day: 15
      month: "*"
      weekday: "*"
      user: sumit
      job: /tmp/script/text.sh   
