---
- name: Kill a process
  hosts: all
  
  tasks:
  - name: Find a process and kill it
    # Is process me agar koi error generate hota hai to ignore kare

    ignore_errors: yes
    shell: "pgrep nginx | xargs kill"   
