---
- name: Install and Start the service
  hosts: all  
  
  tasks:
  - name: Installing nginx
    dnf:
      name: nginx
      state: present
  - name: Starting the nginx service
    service:
      name: nginx
      state: started
      enabled: true
                       
