---
- name: Install and Start the service
  hosts: all
  become: true
  # varible declare karne ka ye fayeda hota hai ki hum ek jagah hi changes karna padtahai   vars: 
    - app: nginx  
  
  tasks:
  - name: Installing nginx
    dnf:
      name: "{{app}}"
      state: present
  - name: Starting the nginx service
    service:
      name: "{{app}}"
      state: started
      enabled: true
  
